### ISSUE TITLE
sdk crashed

### ISSUE THREAD

**Issue by chenzhong13** [bugfender/BugfenderSDK-android-sample#13]
Bugfender sdk version: 3.0.0

crash 1:
![image](https://user-images.githubusercontent.com/5875437/95574566-b896e600-0a5f-11eb-94cc-68b2bc3f3cf9.png)

crash 2:
![image](https://user-images.githubusercontent.com/5875437/95574682-fac02780-0a5f-11eb-8418-875ecad21fde.png)

**Comment by jgimenez** [comment]
Hi there, thanks for reporting this. I see you're not using the latest version of the SDK, although this is not a known problem of version 3.0.0, so it does not necessarily have been resolved. Could you please share the full stacktrace information with us? If you don't want to do it here publicly, please contact us through support.

**Comment by jgimenez** [comment]
Closing due to lack of activity.

**Comment by chenzhong13** [comment]
@jgimenez  We use a thirdparty platform to report crash, it only has these information.

We upgraded your sdk to 3.0.6, and crashes still existed :
your code was obfuscated yourself.

Android OS version: 4.4.4
Rom: samsung/goyavewifixx

![image](https://user-images.githubusercontent.com/5875437/98316019-8a7fd400-2014-11eb-93c8-c5fc29adc336.png)

**Comment by jgimenez** [comment]
Hi there, still we would need the full stacktrace information in order to debug this. This screenshot does not contain the full context of the crash, nor even why it crashed. If you don't want to post the crash details here publicly, please contact us through support.

**Comment by chenzhong13** [comment]
> Hi there, still we would need the full stacktrace information in order to debug this. This screenshot does not contain the full context of the crash, nor even why it crashed. If you don't want to post the crash details here publicly, please contact us through support.

can't you just try catch that line and report the raw string to your server to investage?

**Comment by chenzhong13** [comment]
> > Hi there, still we would need the full stacktrace information in order to debug this. This screenshot does not contain the full context of the crash, nor even why it crashed. If you don't want to post the crash details here publicly, please contact us through support.
> 
> can't you just try catch that line and report the raw string to your server to investage?

your sdk can log the error message to logcat, but should not crash

**Comment by jgimenez** [comment]
I'm sorry, we still need the full crash information in order to be able to help you. Please post it here or contact us privately if you do not want to share it here.
